spring:
 mail:
  host: smtp.gmail.com
  port: 587
  username: "${user.email}"
  password: "${user.pass}"
  properties:
   mail:
    smtp:
     auth: true
     starttls: 
      enable: true
 data:
  mongodb:
   host: localhost
   port: 27017
   database: student-data
 devtools:
  restart:
   enabled: true
 logging:
  level: DEBUG